site_name: hydrodata
site_description: A python project to deal with internal datasources
site_author: WenyuOuyang
site_url: https://WenyuOuyang.github.io/hydrodata
repo_url: https://github.com/WenyuOuyang/hydrodata

copyright: "Copyright &copy; 2023 - 2023 Wenyu Ouyang"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: assets/logo.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    # - git-revision-date-localized:
    #       enable_creation_date: true
    #       type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          # ignore_h1_titles: True
          # execute: True
          # allow_errors: false
          # ignore: ["conf.py"]
          # execute_ignore: ["*ignore.ipynb"]
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Modules:
        - Downloader: downloader.md
        - Processor: processor.md
        - Catalog: catalog.md
        - Reader: reader.md
        - GISTools: gistools.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/iHeadWater/hydrodata/issues
    - Examples:
        - modules/downloader.ipynb
        - modules/catalog.ipynb
        - modules/reader.ipynb
        - modules/minio.ipynb
    - API Reference:
        - Downloader module: 
            - Downloader: api/downloader.md
            - DEM: api/dem.md
        - Catalog module:
            - minio: api/catalog_minio.md
        - Reader module:
            - minio: api/reader_minio.md
    - Resources:
          - hydroGIS: hydrogis.md
